### ISSUE TITLE
Column not found 'additional_table.is_visible_on_checkout' 

### ISSUE THREAD

**Issue by easyMaxi** [firegento/firegento-magesetup#179]
Hi,

when i try to add a product to the cart i receive the following error.
It's a fresh magento 1.9.1.1 with just magesetupand a few other extension.
I guess it's magesetup related. But it's just a guess.
Can someone verify this? And at best tell me what's the problem.
 
```
a:5:{i:0;s:879:"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'additional_table.is_visible_on_checkout' in 'where clause', query was: SELECT `main_table`.`entity_type_id`, `main_table`.`attribute_code`, `main_table`.`attribute_model`, `main_table`.`backend_model`, `main_table`.`backend_type`, `main_table`.`backend_table`, `main_table`.`frontend_model`, `main_table`.`frontend_input`, `main_table`.`frontend_label`, `main_table`.`frontend_class`, `main_table`.`source_model`, `main_table`.`is_required`, `main_table`.`is_user_defined`, `main_table`.`default_value`, `main_table`.`is_unique`, `main_table`.`note`, `additional_table`.* FROM `m15_eav_attribute` AS `main_table`
 INNER JOIN `m15_catalog_eav_attribute` AS `additional_table` ON additional_table.attribute_id = main_table.attribute_id WHERE (main_table.entity_type_id = 4) AND (additional_table.is_visible_on_checkout = '1')";i:1;s:3686:"#0 /lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 /lib/Varien/Db/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 /lib/Zend/Db/Adapter/Abstract.php(737): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `main_ta...', Array)
#6 /lib/Varien/Data/Collection/Db.php(734): Zend_Db_Adapter_Abstract->fetchAll('SELECT `main_ta...', Array)
#7 /app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)
#8 /lib/Varien/Data/Collection/Db.php(566): Mage_Core_Model_Resource_Db_Collection_Abstract->getData()
#9 /lib/Varien/Data/Collection.php(741): Varien_Data_Collection_Db->load()
#10 /app/code/community/FireGento/MageSetup/Model/Observer.php(367): Varien_Data_Collection->getIterator()
#11 /app/code/core/Mage/Core/Model/App.php(1338): FireGento_MageSetup_Model_Observer->addProductAttributesToQuoteItems(Object(Varien_Event_Observer))
#12 /app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(FireGento_MageSetup_Model_Observer), 'addProductAttri...', Object(Varien_Event_Observer))
#13 /app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('sales_quote_con...', Array)
#14 /app/code/core/Mage/Sales/Model/Quote/Config.php(36): Mage::dispatchEvent('sales_quote_con...', Array)
#15 /app/code/core/Mage/Sales/Model/Resource/Quote/Item/Collection.php(181): Mage_Sales_Model_Quote_Config->getProductAttributes()
#16 /app/code/core/Mage/Sales/Model/Resource/Quote/Item/Collection.php(139): Mage_Sales_Model_Resource_Quote_Item_Collection->_assignProducts()
#17 /lib/Varien/Data/Collection/Db.php(581): Mage_Sales_Model_Resource_Quote_Item_Collection->_afterLoad()
#18 /lib/Varien/Data/Collection.php(741): Varien_Data_Collection_Db->load()
#19 /app/code/core/Mage/Sales/Model/Quote.php(758): Varien_Data_Collection->getIterator()
#20 /app/code/core/Mage/Sales/Model/Quote.php(789): Mage_Sales_Model_Quote->getAllItems()
#21 /app/code/core/Mage/Checkout/Model/Cart.php(150): Mage_Sales_Model_Quote->hasItems()
#22 /app/code/core/Mage/Checkout/controllers/CartController.php(143): Mage_Checkout_Model_Cart->init()
#23 /app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_CartController->indexAction()
#24 /app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#25 /app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#26 /app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#27 /app/Mage.php(684): Mage_Core_Model_App->run(Array)
#28 /index.php(87): Mage::run('', 'store')
#29 {main}";s:3:"url";s:15:"/checkout/cart/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}
```

**Comment by easyMaxi** [comment]
Couldn't reproduce the error with a new setup ...

**Comment by galaxist740** [comment]
Hi, 

i have the same error. Only when i activate the firegento extension. In database table eav_attribute there is no column 'additional_table.is_visible_on_checkout'. In file FireGento/MageSetup/Model/Observer.php
on line 365 i find the call.
Who can help me?
