### ISSUE TITLE
Column not found 'additional_table.is_visible_on_checkout'

### ISSUE THREAD

**Issue by galaxist740** [firegento/firegento-magesetup#202]
Hi!
after installing (copy the files from here to my server) there is a error. 
```
a:5:{i:0;s:871:"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'additional_table.is_visible_on_checkout' in 'where clause', query was: SELECT `main_table`.`entity_type_id`, `main_table`.`attribute_code`, `main_table`.`attribute_model`, `main_table`.`backend_model`, `main_table`.`backend_type`, `main_table`.`backend_table`, `main_table`.`frontend_model`, `main_table`.`frontend_input`, `main_table`.`frontend_label`, `main_table`.`frontend_class`, `main_table`.`source_model`, `main_table`.`is_required`, `main_table`.`is_user_defined`, `main_table`.`default_value`, `main_table`.`is_unique`, `main_table`.`note`, `additional_table`.* FROM `eav_attribute` AS `main_table`
 INNER JOIN `catalog_eav_attribute` AS `additional_table` ON additional_table.attribute_id = main_table.attribute_id WHERE (main_table.entity_type_id = 4) AND (additional_table.is_visible_on_checkout = '1')";i:1;s:4396:"#0 /home/www/p166496/html/magento01/magento/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/www/p166496/html/magento01/magento/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/www/p166496/html/magento01/magento/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/www/p166496/html/magento01/magento/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 /home/www/p166496/html/magento01/magento/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 /home/www/p166496/html/magento01/magento/lib/Zend/Db/Adapter/Abstract.php(737): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `main_ta...', Array)
#6 /home/www/p166496/html/magento01/magento/lib/Varien/Data/Collection/Db.php(734): Zend_Db_Adapter_Abstract->fetchAll('SELECT `main_ta...', Array)
#7 /home/www/p166496/html/magento01/magento/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)
#8 /home/www/p166496/html/magento01/magento/lib/Varien/Data/Collection/Db.php(566): Mage_Core_Model_Resource_Db_Collection_Abstract->getData()
#9 /home/www/p166496/html/magento01/magento/lib/Varien/Data/Collection.php(741): Varien_Data_Collection_Db->load()
#10 /home/www/p166496/html/magento01/magento/app/code/community/FireGento/MageSetup/Model/Observer.php(367): Varien_Data_Collection->getIterator()
#11 /home/www/p166496/html/magento01/magento/app/code/core/Mage/Core/Model/App.php(1357): FireGento_MageSetup_Model_Observer->addProductAttributesToQuoteItems(Object(Varien_Event_Observer))
#12 /home/www/p166496/html/magento01/magento/app/code/core/Mage/Core/Model/App.php(1336): Mage_Core_Model_App->_callObserverMethod(Object(FireGento_MageSetup_Model_Observer), 'addProductAttri...', Object(Varien_Event_Observer))
#13 /home/www/p166496/html/magento01/magento/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('sales_quote_con...', Array)
#14 /home/www/p166496/html/magento01/magento/app/code/core/Mage/Sales/Model/Quote/Config.php(36): Mage::dispatchEvent('sales_quote_con...', Array)
#15 /home/www/p166496/html/magento01/magento/app/code/core/Mage/Sales/Model/Resource/Quote/Item/Collection.php(181): Mage_Sales_Model_Quote_Config->getProductAttributes()
#16 /home/www/p166496/html/magento01/magento/app/code/core/Mage/Sales/Model/Resource/Quote/Item/Collection.php(139): Mage_Sales_Model_Resource_Quote_Item_Collection->_assignProducts()
#17 /home/www/p166496/html/magento01/magento/lib/Varien/Data/Collection/Db.php(581): Mage_Sales_Model_Resource_Quote_Item_Collection->_afterLoad()
#18 /home/www/p166496/html/magento01/magento/lib/Varien/Data/Collection.php(741): Varien_Data_Collection_Db->load()
#19 /home/www/p166496/html/magento01/magento/app/code/core/Mage/Sales/Model/Quote.php(758): Varien_Data_Collection->getIterator()
#20 /home/www/p166496/html/magento01/magento/app/code/core/Mage/Sales/Model/Quote.php(789): Mage_Sales_Model_Quote->getAllItems()
#21 /home/www/p166496/html/magento01/magento/app/code/core/Mage/Checkout/Model/Cart.php(150): Mage_Sales_Model_Quote->hasItems()
#22 /home/www/p166496/html/magento01/magento/app/code/local/Customweb/SaferpayCw/Model/Checkout/Cart.php(36): Mage_Checkout_Model_Cart->init()
#23 /home/www/p166496/html/magento01/magento/app/code/core/Mage/Checkout/controllers/CartController.php(143): Customweb_SaferpayCw_Model_Checkout_Cart->init()
#24 /home/www/p166496/html/magento01/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_CartController->indexAction()
#25 /home/www/p166496/html/magento01/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#26 /home/www/p166496/html/magento01/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#27 /home/www/p166496/html/magento01/magento/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#28 /home/www/p166496/html/magento01/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#29 /home/www/p166496/html/magento01/magento/index.php(83): Mage::run('', 'store')
#30 {main}";s:3:"url";s:15:"/checkout/cart/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}
```
This column does not exist in database. Is there an newer version of firegento-magesetup for Magento Version 1.9.2.1?

**Comment by Schrank** [comment]
The current version is 2.2.3 and the column is created by magesetup, so it seems your install scripts didn't run correctly.

**Comment by ahonecker76** [comment]
I did just setup the actual Version on a Magento 1.9.3.7 installation and running into the same problems. I did run it many times, reindexing and cache delete was not use :(

**Comment by Schrank** [comment]
Please check the version in core_resource.

Do you say, you haven't deleted the cache? Do it.

**Comment by ahonecker76** [comment]
I did clean the cache and also reindex before. What you mean with core_resources? - I downloaded the actual package. The file only says firegento-magesetup-development and followed the instructutions. After symlink activated, it appeard, shows doing everything, but not works. at checkout/shoping card. Same error as statet before regarding database, so seems no existing/created table/entry.

**Comment by Schrank** [comment]
core_resource is a database table with the current version of the database setup scripts. If the version is up to date, the script should have run and the column should have been created - which obviously didn't happen.

To fix this, you should reset the version and try again. And for this I recommend someone who knows Magento.

**Comment by ahonecker76** [comment]
Hello. Now it´s November 2018 and another Shop started with fresh clean 1.9.3.10 gives exactly the same error, as soon somebody put an articel into the basket. The problem go away as soon the session is not vaild anymore, and repeating as soon i want to add something to the basket again. What could prevent the script running normaly ? - It shows no errors by the way.

**Comment by Schrank** [comment]
Can you please check, what version of`magesetup_setup` is in your core_resource?

**Comment by ahonecker76** [comment]
According to the core_resource table this are the magesetup entrys. 
magemenu_setup | 1.5.0 | 1.5.0
magesetup_setup | 2.4.2 | 2.4.2

Thank you for any help in advance

**Comment by Schrank** [comment]
The missing table is installed here:
https://github.com/firegento/firegento-magesetup/blob/development/src/app/code/community/FireGento/MageSetup/sql/magesetup_setup/mysql4-upgrade-1.0.4-1.0.5.php#L40-L50

And if this would be a global problem, we would have a lot more complaints, therefore I have not clue what's going on on your system but I don't see anything I can do for you neither :-/

**Comment by ahonecker76** [comment]
After i deinstalled and re-installed also no luck. BUT, you 100% solved my problem. I just added the column according to your information manually; It works now. Thank you very much.
