### ISSUE TITLE
Magento 1.7 Compatibility

### ISSUE THREAD

**Issue by nickw108** [firegento/firegento-magesetup#98]
I just installed the latest version from GitHub on a Magento 1.7.0.2 store and get the following error:

    Error in file: "/html/live/app/code/community/FireGento/MageSetup/sql/magesetup_setup/mysql4-install-0.5.0.php" - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '82-General' for key 'UNQ_EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_NAME'

    Trace:
    #0 /html/live/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')
    #1 /html/live/app/code/core/Mage/Core/Model/Resource/Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb('install', '', '2.1.1')
    #2 /html/live/app/code/core/Mage/Core/Model/Resource/Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('2.1.1')
    #3 /html/live/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
    #4 /html/live/app/code/core/Mage/Core/Model/App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
    #5 /html/live/app/code/core/Mage/Core/Model/App.php(343): Mage_Core_Model_App->_initModules()
    #6 /html/live/app/Mage.php(683): Mage_Core_Model_App->run(Array)
    #7 /html/live/index.php(87): Mage::run('', 'store')
    #8 {main}

Not sure if this is a compatibility issue with Magento 1.7. Then maybe the easiest approach would be to use the old GermanSetup until the client has been upgraded to the latest version of Magento. Or maybe this has nothing to do at all with 1.7 and is just due to database issues?

**Comment by therouv** [comment]
Closing because of inactivity and the fact that it is no MageSetup problem.
